### ISSUE TITLE
ability to add subcategories

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-accordion#3]
Hello,

At the moment you can only specify one title and text meaning that you can only make one category but not subcategories for that current title. I would like to see a ability to create subcategories/titles f.ex;

```
Title1
text1
 Title 1.1
  text1.1
   Title 1.1a
    text 1.1a
 Title 1.2
  text 1.2 
Title2
text2
Title3
text3
```

**Comment by thomasmars** [comment]
How do you suggest this should look in the editor ? The changes must be backwards compatible, so this would mean that you must be able to add a text at the second level, and the possibility of creating a new accordion there. Anyone interested in creating a pull request for this must take this into account.

**Comment by Jarvil** [comment]
I don't know, someone can figure it out :)

**Comment by roblespar** [comment]
Feature request? Nested Accordion
I think it would be good to have one more nested layer of accordion objects. "Add Subpanel" under the text box. Too many and it gets to visually complicated.

**Comment by thomasmars** [comment]
We try to track feature requests through https://h5p.org/forum/16 so they are available to a broader audience, and primarily use github for pull requests. Please open an issue there.
