### ISSUE TITLE
font size for titel of panel are not rendered corretly

### ISSUE THREAD

**Issue by tholudwig** [h5p/h5p-accordion#36]
The setting of the font size (h2, h3 or h4) for the title of the panel is adopted. However, all three font sizes are rendered in the same size.

Here are some example screenshots:

Thanks a lot for the awesome work.
![example_h2](https://user-images.githubusercontent.com/14368866/68299722-8e44e780-009c-11ea-8641-d63b58660be2.png)

![example_h4](https://user-images.githubusercontent.com/14368866/68299829-c3e9d080-009c-11ea-88d9-36deb9acb37a.png)

**Comment by otacke** [comment]
@tholudwig I don't think this is a bug given the hint in the editor: https://github.com/h5p/h5p-accordion/blob/master/semantics.json#L40

> The h tag used on the labels. Normally H2 but if this belongs under an H2 heading use H3. Does not affect the size of the labels, only used for semantical purposes.

**Comment by thomasmars** [comment]
Correct, to change the size of the font you would have to use css.

**Comment by csidirop** [comment]
But whats the purpose of those tags when they don't alter the appearance? What are those "semantical purposes"?

**Comment by otacke** [comment]
@csidirop Accessibility. Screen readers announce the level and thus give context.

**Comment by csidirop** [comment]
Okay thats fine, but whats wrong with rendering the h tags like its done in the text element

**Comment by otacke** [comment]
@csidirop Throughout the accordion, you do not have different h-sizes, just one. Visually, an accordion is an accordion no matter what the position in the page hierarchy is. I assume that this is the reason why there's no different among h-tags visually. I'd not have used h-tags here to begin with, but here they are. And now I'd have to dive into what WCAG demands for the use of h-tags and the trouble that H5P content sitting inside of an iframe creates and why you can choose the tag ...
